In [1]:
import numpy as np
import pandas as pd

DATA CLEANING

In [2]:
df_orders=pd.read_csv(r"C:\Users\ROHAN SINGH\Downloads\archive (4)\Ecommerce Order Dataset\train\df_Orders.csv")

In [3]:
df_orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18
...,...,...,...,...,...,...,...
89311,zlcLnXGgAabl,bfJtzkBGksdY,delivered,2018-08-19 17:25:36,2018-08-21 04:35:30,2018-08-30 14:47:46,2018-09-04
89312,IlTAoIkILwrq,4hjsCpj6FC7g,delivered,2017-12-15 11:20:27,2017-12-16 02:37:32,2017-12-20 19:23:40,2018-01-04
89313,uA6oXfftGVmT,DLn56oKHl9bv,delivered,2018-07-24 06:39:14,2018-07-24 11:20:39,2018-07-27 01:41:40,2018-08-01
89314,v3QtU6xlGDJp,auSfRYUQUOIq,delivered,2018-08-11 08:04:22,2018-08-11 08:24:40,2018-08-14 21:43:51,2018-08-17
89315,Xo1fqyXOC6CR,rhevVNXYJnEs,delivered,2018-06-09 21:46:58,2018-06-09 22:19:00,2018-06-14 15:03:46,2018-07-05

In [4]:
df_payments=pd.read_csv(r"C:\Users\ROHAN SINGH\Downloads\archive (4)\Ecommerce Order Dataset\train\df_Payments.csv")

In [5]:
df_payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15
...,...,...,...,...,...
89311,zlcLnXGgAabl,1,wallet,1,128.00
89312,IlTAoIkILwrq,1,wallet,1,106.86
89313,uA6oXfftGVmT,1,credit_card,1,376.39
89314,v3QtU6xlGDJp,1,voucher,1,48.05
89315,Xo1fqyXOC6CR,1,credit_card,10,211.93

In [6]:
df_products=pd.read_csv(r"C:\Users\ROHAN SINGH\Downloads\archive (4)\Ecommerce Order Dataset\train\df_Products.csv")

In [7]:
df_products

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0
4,1lycYGcsic2F,toys,300.0,17.0,4.0,12.0
...,...,...,...,...,...,...
89311,W8vikEizUggJ,toys,700.0,21.0,14.0,14.0
89312,KXSbyJWtMMwZ,toys,600.0,16.0,16.0,16.0
89313,EG4wDSpFyTth,health_beauty,250.0,22.0,10.0,18.0
89314,ZWyg4uNWPHjJ,toys,250.0,16.0,2.0,11.0
89315,5pbzE0rDy61l,toys,1750.0,32.0,18.0,24.0

In [8]:
df_customers=pd.read_csv(r"C:\Users\ROHAN SINGH\Downloads\archive (4)\Ecommerce Order Dataset\train\df_Customers.csv")

In [9]:
df_customers

,customer_id,customer_zip_code_prefix,customer_city,customer_state
0,hCT0x9JiGXBQ,58125,varzea paulista,SP
1,PxA7fv9spyhx,3112,armacao dos buzios,RJ
2,g3nXeJkGI0Qw,4119,jandira,SP
3,EOEsCQ6QlpIg,18212,uberlandia,MG
4,mVz5LO2Vd6cL,88868,ilhabela,SP
...,...,...,...,...
89311,bfJtzkBGksdY,94060,amparo,SP
89312,4hjsCpj6FC7g,99835,itapevi,SP
89313,DLn56oKHl9bv,2540,sao paulo,SP
89314,auSfRYUQUOIq,12288,paulinia,SP
89315,rhevVNXYJnEs,93048,brasilia,DF

In [10]:
df_orderitems=pd.read_csv(r"C:\Users\ROHAN SINGH\Downloads\archive (4)\Ecommerce Order Dataset\train\df_OrderItems.csv")

In [11]:
df_orderitems

           order_id    product_id     seller_id    price  shipping_charges
0      Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF   223.51             84.65
1      v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs   170.80             23.79
2      Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD    64.40             17.38
3      bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf   264.50             30.72
4      Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr   779.90             30.66
...             ...           ...           ...      ...               ...
89311  zlcLnXGgAabl  W8vikEizUggJ  2QjevWskirjm    31.99            188.65
89312  IlTAoIkILwrq  KXSbyJWtMMwZ  BFS9XJPapWv0   282.00              1.64
89313  uA6oXfftGVmT  EG4wDSpFyTth  TuPm19CMKvrM    58.10              4.09
89314  v3QtU6xlGDJp  ZWyg4uNWPHjJ  yGbPyLPc8PmT  2899.00            113.01
89315  Xo1fqyXOC6CR  5pbzE0rDy61l  mkWN70fui2ro    37.88             70.06

[89316 rows x 5 columns]

In [12]:
df_orders.head()
df_orders.info()
df_orders.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  object
 4   order_approved_at              89307 non-null  object
 5   order_delivered_timestamp      87427 non-null  object
 6   order_estimated_delivery_date  89316 non-null  object
dtypes: object(7)
memory usage: 4.8+ MB

(89316, 7)

In [13]:
df_orders.duplicated().sum()

0

In [14]:
df_orders[['order_purchase_timestamp', 'order_approved_at', 'order_delivered_timestamp', 'order_estimated_delivery_date']].head()

,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18

In [15]:
date_cols = ['order_purchase_timestamp', 'order_approved_at', 
             'order_delivered_timestamp', 'order_estimated_delivery_date']

for col in date_cols:
    df_orders[col] = pd.to_datetime(df_orders[col])

df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  datetime64[ns]
 4   order_approved_at              89307 non-null  datetime64[ns]
 5   order_delivered_timestamp      87427 non-null  datetime64[ns]
 6   order_estimated_delivery_date  89316 non-null  datetime64[ns]
dtypes: datetime64[ns](4), object(3)
memory usage: 4.8+ MB

In [16]:
df_payments.head()
df_payments.info()
df_payments.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              89316 non-null  object
 1   payment_sequential    89316 non-null  int64
 2   payment_type          89316 non-null  object
 3   payment_installments  89316 non-null  int64
 4   payment_value         89316 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.4+ MB

(89316, 5)

In [17]:
df_payments['order_id'].duplicated().sum()

0

In [18]:
df_payments.duplicated().sum()

0

In [19]:
df_products.head()
df_products.info()
df_products.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             89316 non-null  object
 1   product_category_name  89008 non-null  object
 2   product_weight_g       89301 non-null  float64
 3   product_length_cm      89301 non-null  float64
 4   product_height_cm      89301 non-null  float64
 5   product_width_cm       89301 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.1+ MB

(89316, 6)

In [20]:
df_products['product_id'].nunique()

27451

In [21]:
df_products.duplicated().sum()

61865

In [22]:
df_products[df_products['product_weight_g'].isnull()]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
2150,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
7473,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
13628,VqyFCmRtRdfR,toys,NaN,NaN,NaN,NaN
28114,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
32791,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
38130,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
39021,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
49124,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
55696,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
56195,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
57156,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
63531,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
68946,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
70321,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
88303,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN

In [23]:
product_clean=df_products.drop_duplicates()
product_clean

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0
4,1lycYGcsic2F,toys,300.0,17.0,4.0,12.0
...,...,...,...,...,...,...
89291,USSzekoHkA25,toys,1352.0,37.0,9.0,30.0
89297,SZRgDV7xa2U8,toys,1360.0,28.0,21.0,24.0
89303,w2OtdEjwNHBr,toys,833.0,17.0,12.0,16.0
89311,W8vikEizUggJ,toys,700.0,21.0,14.0,14.0
89315,5pbzE0rDy61l,toys,1750.0,32.0,18.0,24.0

In [24]:
product_clean[product_clean['product_weight_g'].isnull()]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
2150,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
13628,VqyFCmRtRdfR,toys,NaN,NaN,NaN,NaN

In [25]:
product_clean = product_clean.dropna(subset=['product_length_cm'])
product_clean.shape

(27449, 6)

In [26]:
product_clean['product_category_name'].isnull().sum()

141

In [27]:
product_clean['product_category_name'] = product_clean['product_category_name'].fillna('unknown')

C:\Users\ROHAN SINGH\AppData\Local\Temp\ipykernel_10360\3169194294.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_clean['product_category_name'] = product_clean['product_category_name'].fillna('unknown')

In [30]:
product_clean['product_category_name'].isnull().sum()

0

In [33]:
df_customers.head()
df_customers.info()
df_customers.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  object
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  object
 3   customer_state            89316 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.7+ MB

(89316, 4)

In [34]:
df_customers['customer_id'].nunique()

89316

In [35]:
df_customers.duplicated().sum()

0

In [41]:
df_customers.isnull().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [42]:
df_orderitems.head()
df_orderitems.info()
df_orderitems.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  object
 1   product_id        89316 non-null  object
 2   seller_id         89316 non-null  object
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), object(3)
memory usage: 3.4+ MB

(89316, 5)

In [43]:
df_orderitems['order_id'].nunique()

89316

In [44]:
df_orderitems.duplicated().sum()

0

In [45]:
df_orderitems[['price', 'shipping_charges']].describe()

              price  shipping_charges
count  89316.000000      89316.000000
mean     340.900543         44.283210
std      557.459897         37.672491
min        0.850000          0.000000
25%       59.650000         20.110000
50%      136.900000         35.055000
75%      399.200000         57.190000
max     6735.000000        409.680000

JOINING TABLE

In [46]:
df=pd.merge(df_orders,df_customers,on='customer_id',how='left')

In [47]:
df.shape

(89316, 10)

In [48]:
df = df.merge(df_orderitems, on='order_id', how='left')

In [49]:
df.shape

(89316, 14)

In [52]:
df = df.merge(product_clean, on='product_id', how='left')

In [53]:
df.shape

(89316, 19)

In [54]:
df = df.merge(df_payments, on='order_id', how='left')

In [55]:
df.shape

(89316, 23)

In [56]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
product_id                          0
seller_id                           0
price                               0
shipping_charges                    0
product_category_name              15
product_weight_g                   15
product_length_cm                  15
product_height_cm                  15
product_width_cm                   15
payment_sequential                  0
payment_type                        0
payment_installments                0
payment_value                       0
dtype: int64

In [58]:
df['product_category_name'] = df['product_category_name'].fillna('unknown')

for col in ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']:
    df[col] = df[col].fillna(df[col].mean())

In [60]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
product_id                          0
seller_id                           0
price                               0
shipping_charges                    0
product_category_name               0
product_weight_g                    0
product_length_cm                   0
product_height_cm                   0
product_width_cm                    0
payment_sequential                  0
payment_type                        0
payment_installments                0
payment_value                       0
dtype: int64

CREATING USEFUL COLUMNS

In [62]:
# Delivery time (days between purchase and delivery)
df['delivery_time_days']=(df['order_delivered_timestamp']-df['order_purchase_timestamp']).dt.days

In [63]:
#Delivery delay (negative = early, positive = late)
df['delivery_delay_days'] = (df['order_delivered_timestamp'] - df['order_estimated_delivery_date']).dt.days

In [64]:
#Order month/year
df['order_year'] = df['order_purchase_timestamp'].dt.year
df['order_month'] = df['order_purchase_timestamp'].dt.month

In [65]:
#Total order value (price + shipping)
df['total_order_value'] = df['price'] + df['shipping_charges']

In [66]:
df[['delivery_time_days', 'delivery_delay_days', 'order_year', 'order_month', 'total_order_value']].describe()

,delivery_time_days,delivery_delay_days,order_year,order_month,total_order_value
count,87427.000000,87427.000000,89316.000000,89316.000000,89316.000000
mean,11.969129,-12.132442,2017.533006,6.027834,385.183753
std,9.277678,10.041470,0.505445,3.233420,558.492266
min,0.000000,-147.000000,2016.000000,1.000000,1.140000
25%,6.000000,-17.000000,2017.000000,3.000000,107.710000
50%,10.000000,-13.000000,2018.000000,6.000000,184.650000
75%,15.000000,-7.000000,2018.000000,8.000000,437.860000
max,209.000000,188.000000,2018.000000,12.000000,6738.820000

In [67]:
df.sort_values('delivery_delay_days', ascending=False).head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,customer_zip_code_prefix,customer_city,customer_state,...,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,delivery_time_days,delivery_delay_days,order_year,order_month,total_order_value
68448,I7Uy2GUAWB08,6QXA9Gqv1Mqz,delivered,2018-02-23 14:57:35,2018-02-23 15:16:14,2018-09-19 23:24:07,2018-03-15,3893,rio de janeiro,RJ,...,22.0,1,credit_card,1,135.50,208.0,188.0,2018,2,60.83
571,pWRjBubXBYdq,IgFTw1gGD2PM,delivered,2017-02-21 23:31:27,2017-02-23 02:35:15,2017-09-19 14:36:39,2017-03-22,3251,montanha,ES,...,11.0,1,wallet,1,46.52,209.0,181.0,2017,2,448.72
87475,PLhufnwqAyZ0,c1DFqTJCKwN3,delivered,2017-03-15 23:23:17,2017-03-15 23:23:17,2017-09-19 17:14:25,2017-04-10,2717,perdizes,MG,...,45.0,1,credit_card,1,2.29,187.0,162.0,2017,3,86.92
25607,axwHLmxXXvCg,AWJ6El4M6szG,delivered,2017-06-12 13:14:11,2017-06-12 13:25:11,2017-12-04 18:36:29,2017-06-26,8275,sao bernardo do campo,SP,...,35.0,1,voucher,1,145.48,175.0,161.0,2017,6,200.90
3145,l7IXVGR1psXu,bcH6hIBROSup,delivered,2017-03-15 11:24:27,2017-03-15 11:24:27,2017-09-19 14:38:18,2017-04-13,84220,aracaju,SE,...,12.0,1,wallet,1,26.74,188.0,159.0,2017,3,451.07

EXPLORATORY DATA ANALYSIS

In [68]:
#Revenue By Month
df.groupby(['order_year', 'order_month'])['total_order_value'].sum().reset_index()

    order_year  order_month  total_order_value
0         2016            9            1125.64
1         2016           10          109840.01
2         2016           12             277.26
3         2017            1          281577.74
4         2017            2          517698.87
5         2017            3          942034.30
6         2017            4          834530.47
7         2017            5         1185649.97
8         2017            6         1045162.92
9         2017            7         1387588.24
10        2017            8         1450569.89
11        2017            9         1604889.14
12        2017           10         1621871.22
13        2017           11         3156467.19
14        2017           12         2008941.70
15        2018            1         2313116.76
16        2018            2         2276044.40
17        2018            3         2616873.69
18        2018            4         2459057.79
19        2018            5         2651374.08
20        2018            6         1972822.19
21        2018            7         2008237.28
22        2018            8         1957085.57
23        2018            9             235.74

Revenue grew steadily from late 2016 through 2018, peaking around November 2017 (₹31.5L) and stabilizing at ₹20-26L/month through mid-2018. September 2018 shows only ₹235 due to partial data collection at the end of the dataset.

In [74]:
#Top 10 product categories by revenue
df.groupby('product_category_name')['total_order_value'].sum().sort_values(ascending=False).head(10)

product_category_name
toys                     25965415.24
furniture_decor            832070.19
garden_tools               780355.10
bed_bath_table             699715.68
health_beauty              697498.49
watches_gifts              636302.58
sports_leisure             626172.99
telephony                  530039.29
computers_accessories      504251.35
housewares                 474102.13
Name: total_order_value, dtype: float64

75% of orders are labeled under the "toys" category, an implausible concentration compared to all other categories combined. This is likely a placeholder/default value in the source data rather than an accurate label.

In [77]:
# Payment method distribution
df['payment_type'].value_counts(normalize=True) * 100

credit_card    73.686685
wallet         19.371669
voucher         5.498455
debit_card      1.443190
Name: payment_type, dtype: float64

Credit card dominates at ~74% of all payments 

Wallet is a distant second at ~19%

Voucher (5.5%) and debit card (1.4%) are minor payment methods

In [79]:
# Delivery performance 
df['delivery_delay_days'].apply(lambda x: 'Late' if x > 0 else 'On-time/Early')
df['delivery_status'].value_counts(normalize=True) * 100

On-time/Early    93.724529
Late              6.275471
Name: delivery_status, dtype: float64

Approx 94% delivery is on time and 6% are late it means the delivery performance is very good.

In [81]:
# Revenue/orders by state
df.groupby('customer_state')['total_order_value'].sum().sort_values(ascending=False).head(10)

customer_state
SP    14586002.19
RJ     4347299.47
MG     3972702.51
RS     1884154.76
PR     1807890.25
SC     1210286.60
BA     1204627.99
GO      768086.19
ES      695583.59
DF      641402.17
Name: total_order_value, dtype: float64

Sao Paulo (SP) accounts for the largest share of revenue (~₹1.46 crore), consistent with it having the highest customer base (37,879 customers). RJ and MG follow as the next largest markets.

In [87]:
df_orderitems

           order_id    product_id     seller_id    price  shipping_charges
0      Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF   223.51             84.65
1      v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs   170.80             23.79
2      Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD    64.40             17.38
3      bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf   264.50             30.72
4      Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr   779.90             30.66
...             ...           ...           ...      ...               ...
89311  zlcLnXGgAabl  W8vikEizUggJ  2QjevWskirjm    31.99            188.65
89312  IlTAoIkILwrq  KXSbyJWtMMwZ  BFS9XJPapWv0   282.00              1.64
89313  uA6oXfftGVmT  EG4wDSpFyTth  TuPm19CMKvrM    58.10              4.09
89314  v3QtU6xlGDJp  ZWyg4uNWPHjJ  yGbPyLPc8PmT  2899.00            113.01
89315  Xo1fqyXOC6CR  5pbzE0rDy61l  mkWN70fui2ro    37.88             70.06

[89316 rows x 5 columns]

In [88]:
from sqlalchemy import create_engine

username = "postgres"
password = "rohan123"
host = "localhost"
port = "5432"
database = "ecommerce"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

print("Connected Successfully!")

Connected Successfully!

In [89]:
df_orders.to_sql("orders", engine, if_exists="replace", index=False)

df_payments.to_sql("payments", engine, if_exists="replace", index=False)

product_clean.to_sql("products", engine, if_exists="replace", index=False)

df_customers.to_sql("customers", engine, if_exists="replace", index=False)

df_orderitems.to_sql("order_items", engine, if_exists="replace", index=False)

print("All tables uploaded successfully!")

All tables uploaded successfully!